services:
  - type: web
    name: dgs-system.app
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: SESSIONSECRET
        generateValue: true
      - key: PGHOST
        sync: false
      - key: PGDATABASE
        sync: false
      - key: PGUSER
        sync: false
      - key: PGPASSWORD
        sync: false
